-- Contains all SEARCH Hospital Caste Data

insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (1,'Rajgond', 'Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (2,'Madiya Gond', 'Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (3,'Madiya', 'Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (4,'Gayata', 'Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (5,'Pardhan', 'Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (6,'Naik Gond', 'Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (7,'Korku Gond', 'Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (8,'Gond Gowari', 'Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (9,'Halaba','Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (10,'Halabi','Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (11,'Gowari','Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (12,'Mana','Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (13,'Gond','Tribal', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (14,'Mahar','SC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (15,'Navabauddha','SC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (16,'Chambhar','SC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (17,'Mang','SC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (18,'Madagi','SC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (19,'Bhangi','SC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (20,'Khatik','SC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (21,'Teli','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (22,'Kunabi','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (23,'Maral','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (24,'Mali','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (25,'Dhiwar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (26,'Kewat','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (27,'Koli','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (28,'Komati','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (29,'Gandali','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (30,'Koshti','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (31,'Halaba Koshti','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (32,'Lohar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (33,'Sonar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (34,'Kalar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (35,'Nhavi','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (36,'Dhobi (Varathi)','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (37,'Khaati','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (38,'Bhaat','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (39,'Dhanagar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (40,'Gawali','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (41,'Gawandi','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (42,'Kumbhar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (43,'Petki','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (44,'Shimpi','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (45,'Sutar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (46,'Kurmar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (47,'Panchal','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (48,'Devaangaan','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (49,'Zade','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (50,'Vairagi','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (51,'Kohali','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (52,'Vir','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (53,'Uram','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (54,'Jangam','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (55,'Kshatriy','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (56,'Powar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (57,'Banjara','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (58,'Kasar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (59,'Pahad','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (60,'Kahar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (61,'Bari','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (62,'Gurav','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (63,'Vanamali','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (64,'Golakar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (65,'Burud','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (66,'Lingayat','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (67,'Reddi','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (68,'Padmashali','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (69,'Munda','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (70,'Kapewar','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (71,'Vaishya','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (72,'Waaghari','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (73,'Aarak','OBC', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (74,'Gosavi','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (75,'Beldar','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (76,'Garudi','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (77,'Brahman','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (78,'Maratha','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (79,'Musalman','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (80,'Khoja','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (81,'Khrishchan','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (82,'Shikh','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (83,'Panjabi','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (84,'Bangali','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (85,'Jain','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (86,'Talangu','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (87,'Rajput','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (88,'Pardeshi','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (89,'Jogi','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (90,'Marwadi','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (91,'Gujrati','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (92,'Sindhi','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (93,'Thakur','Others', now());
insert into SEARCH_Caste(caste_id, caste_name, caste_type, last_updated_on) values (94,'Sahu','Others', now());